local_costmap: {
  global_frame: map,
  robot_base_frame: base_link,
  update_frequency: 10.0,
  publish_frequency: 10.0,
  transform_tolerance: 25,
  static_map: false,
  rolling_window: true,
  width: 5.0,
  height: 5.0,
  resolution: 0.05 }